# Generated by Django 5.2.4 on 2025-07-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bronewsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bronewsapp.publisher'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_journalist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='sub_journalist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_publisher',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='sub_publisher', to='bronewsapp.publisher'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
