# Generated by Django 5.2.4 on 2025-07-28 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
        ('bronewsapp', '0004_article_content_newsletter_content_publisher_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_journalist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_publisher',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='subscribers', to='bronewsapp.publisher'),
        ),
    ]
