# Generated by Django 5.2.4 on 2025-07-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bronewsapp', '0003_alter_article_author_alter_newsletter_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
